# Site Settings
author: Alexandre Mutel
title: xoofx
description: xoofx website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://xoofx.com" # the base hostname & protocol for your site
encoding: UTF-8

# Github repository
github_user: xoofx
github_repo_url: https://github.com/xoofx/xoofx.github.io/

# Twitter
twitter_user: xoofx
twitter_tweet_button: true

# Jekyll settings
permalink: /blog/:year/:month/:day/:title/
# try to fix excerpt separator
excerpt_separator: "" 
# excerpt_link: Read More...
paginate: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter_opts:
      disable : true
highlighter: rouge

sass:
   style: :compressed
   sourcemap: never

gems:
  - jekyll-sitemap

